src/models/base.py
from datetime import datetime

from sqlalchemy import Column, DateTime, Integer, MetaData
from sqlalchemy.orm import DeclarativeBase


class BaseModel(DeclarativeBase):
    """Base model with default columns."""
    __abstract__ = True

    id = Column(Integer, primary_key=True, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)

    metadata = MetaData(naming_convention={
        "ix": 'ix_%(column_0_label)s',
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s"
    })

src/models/snippet.py
from src.db import db, Column
from src.models.base import BaseModel


class SnippetModel(BaseModel):
    """Code snippet model."""

    __tablename__ = 'code_snippets'

    name = Column(db.String(120), nullable=False)
    language = Column(db.String(50), nullable=False)
    code = Column(db.Text(), nullable=False)

src/modules/add_snippet/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField
from flask_codemirror.fields import CodeMirrorField

from src.config import settings


language_choices = (
    ("python", "Python"),
    ("javascript", "JavaScript"),
    ("go", "Go")
)


class AddSnippetForm(FlaskForm):
    name = StringField()
    language = SelectField(choices=language_choices)
    code = CodeMirrorField(language='python')

src/app.py
from flask import Flask

from src.db import db
from src.config import settings
from src.modules import blueprints
from src.extensions import extensions, extensions_with_db


def import_models() -> None:
    """
    Import all models from src/models.

    :return: None
    """
    from src.models.snippet import SnippetModel


def register_extensions(app: Flask) -> None:
    """
    Register Flask extensions.

    :param app: Flask application instance
    :return: None
    """
    for extension in extensions:
        extension.init_app(app=app)

    for extension in extensions_with_db:
        extension.init_app(app=app, db=db)


def register_blueprints(app: Flask) -> None:
    """
    Method to register list of blueprints to the app.

    :param app: Flask application
    :return: None
    """
    if not blueprints and app.get("CHECK_FOR_BLUEPRINTS") is True:
        message = "The list of blueprints is empty. App won't have any blueprints."
        app.logger.warning(message)
    else:
        for blueprint in blueprints:
            app.register_blueprint(blueprint)


def create_app():
    """Create Flask application."""
    app = Flask(__name__)
    app.config.from_object(settings)

    import_models()

    register_extensions(app)
    register_blueprints(app)

    return app

src/crud/__init__.py
from src.crud.snippet import snippet

src/modules/__init__.py
from src.modules.index.views import index_blueprint
from src.modules.add_snippet.views import add_snippet_blueprint
from src.modules.typer.views import typer_blueprint

blueprints = [index_blueprint, add_snippet_blueprint, typer_blueprint]

src/modules/add_snippet/views.py
from flask import Blueprint, render_template, flash, redirect, url_for

from src import crud
from src.models.snippet import SnippetModel
from src.modules.add_snippet.forms import AddSnippetForm

add_snippet_blueprint = Blueprint(
    'add_snippet',
    __name__,
    template_folder='templates/add_snippet',
)


@add_snippet_blueprint.route('/add-snippet', methods=['GET', 'POST'])
def index():
    form = AddSnippetForm()

    if form.validate_on_submit():
        if form.code.data == "":
            flash("Code field can't be empty", "error")
            return render_template('add_snippet.html', form=form)

        snippet = SnippetModel(
            name=form.name.data,
            language=form.language.data,
            code=form.code.data
        )
        crud.snippet.create(obj_new=snippet)
        flash('Snippet added successfully', 'success')

        return redirect(url_for("index.index"))

    return render_template('add_snippet.html', form=form)

src/modules/index/views.py
import random

from flask import Blueprint, render_template, redirect

from src.crud import snippet

index_blueprint = Blueprint(
    'index',
    __name__,
    template_folder='templates/index',
)


@index_blueprint.route('/', methods=['GET'])
def index():
    snippets = snippet.get_multi()
    return render_template('index.html', snippets=snippets)

src/modules/typer/views.py
from flask import Blueprint, render_template, abort

from src.crud import snippet

typer_blueprint = Blueprint(
    'typer',
    __name__,
    template_folder='templates/typer',
    url_prefix="/snippet"
)


@typer_blueprint.route('/<int:snippet_id>', methods=['GET'])
def typer(snippet_id: int):
    snippet_obj = snippet.get(_id=snippet_id)

    if not snippet_obj:
        abort(404)

    return render_template('typer.html', snippet=snippet_obj)

src/templates/layout.html
<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="referrer" content="no-referrer-when-downgrade">
    <meta name="description" content="Code Typer is a minimalistic code typing game, where you can practice your code typing skills and improve productivity, accuracy and speed.">
    <meta name="robots" content="all">
    <meta name="copyright" content="Nikoloz Naskidashvili">
    <meta name="address" content="Georgia, Tbilisi">
    <meta property="og:locale" content="ka-GE">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Code Typer">
    <meta property="og:description" content="Code Typer is a minimalistic code typing game, where you can practice your code typing skills and improve productivity, accuracy and speed.">
    <meta property="og:url" content="{{ request.base_url }}">
    <meta property="og:site_name" content="Code Typer is a minimalistic code typing game, where you can practice your code typing skills and improve productivity, accuracy and speed.">

    <title>{% block title %}{% endblock %} — Code Typer</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.3/dist/full.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>

    {% block head %}{% endblock %}
</head>
<body class="p-8" tabindex="-1">
    <div class="navbar bg-base-100">
      <div class="flex-1">
          <a class="btn btn-ghost text-xl" href="{{ url_for('index.index') }}">Code Typer</a>
      </div>
      <div class="flex-none">
          <ul class="menu menu-horizontal px-1">
              <li>
                  <a href="{{ url_for('index.index') }}">Home</a>
              </li>
              <li>
                  <a href="{{ url_for('add_snippet.index') }}">Add Snippet</a>
              </li>
          </ul>
      </div>
    </div>

    <div class="px-6">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
                <div role="alert" class="alert alert-{{ category }} my-2 mb-6">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
    </div>

    <div class="page_content px-6 mb-4">
        {% block content %}{% endblock %}
        {% block body %}{% endblock %}
    </div>

    <div class="mobile_content flex flex-col justify-center items-center py-16 w-full text-center">
        Who on earth uses a mobile to write code?
        <br>
        Grab your laptop G!
        <br>
        <br>
        <iframe src="https://giphy.com/embed/pH6bOPv3NRePOlt5Qn" width="400" height="320" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
    </div>
</body>
</html>